name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U numpy scipy tqdm pytest
          pip install -U torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e .
      - name: Run tests
        run: pytest -q